[api]
enabled = true
address = "0.0.0.0:8686"

# SOURCES

[sources.internal_metrics]
type = "internal_metrics"

[sources.metrics]
type = "prometheus_scrape"
endpoints = ["http://exporter-edge:7777/metrics"]

# SINKS

[sinks.vector]
type = "vector"
inputs = ["internal_metrics", "metrics"]
address = "vector-mid:6000"

[sinks.log-console]
inputs = ["internal_metrics", "metrics"]
encoding.codec = "text"
type = "console"
